### ISSUE TITLE
Figure1.pdf

### ISSUE THREAD

**Issue by gael-millot** [CADDE-CENTRE/Novel-SARS-CoV-2-P1-Lineage-in-Brazil#1]
Fig1.pdf is not the same as in https://virological.org/t/genomic-characterisation-of-an-emergent-sars-cov-2-lineage-in-manaus-preliminary-findings/586
Which one is the good one?
Thanks

**Comment by CADDE-CENTRE** [comment]
Please consider this updated figure from Virological https://github.com/CADDE-CENTRE/Novel-SARS-CoV-2-P1-Lineage-in-Brazil/blob/main/Figure1_new_v3.pdf
Thanks for the warning @gael-millot

**Comment by gael-millot** [comment]
Thanks !
